site_name: Starlite
repo_url: https://github.com/starlite-api/starlite
repo_name: starlite-api/starlite
site_url: https://starlite-api.github.io/starlite
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: mirage
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: mirage-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  favicon: images/starlite-favicon.ico
  logo: images/2x/starlite-icon@2x.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search:
        lang: en
    - social:
        cards_color:
          fill: "#1d2433"
          text: "#d6dbe1"
        cards_font: Tahoma
extra_css:
  - css/extra.css
nav:
  - Overview:
      - index.md
      - Project Governance: governance.md
      - Contribution Guide: contributing.md
      - License: license.md
  - Usage:
      - The Starlite App:
          - usage/0-the-starlite-app/0-the-starlite-app.md
          - usage/0-the-starlite-app/1-startup-and-shutdown.md
          - usage/0-the-starlite-app/2-using-application-state.md
          - usage/0-the-starlite-app/3-static-files.md
          - usage/0-the-starlite-app/4-logging.md
      - Routing:
          - usage/1-routing/0-routing.md
          - usage/1-routing/1-registering-routes.md
          - usage/1-routing/2-routers.md
          - usage/1-routing/3-controllers.md
          - usage/1-routing/4-registering-components-multiple-times.md
      - Route Handlers:
          - usage/2-route-handlers/0_route_handlers_concept.md
          - usage/2-route-handlers/1_http_route_handlers.md
          - usage/2-route-handlers/2_websocket_route_handlers.md
          - usage/2-route-handlers/3_asgi_route_handlers.md
      - Parameters:
          - usage/3-parameters/0-path-parameters.md
          - usage/3-parameters/1-query-parameters.md
          - usage/3-parameters/2-header-and-cookie-parameters.md
          - usage/3-parameters/3-the-parameter-function.md
          - usage/3-parameters/4-layered-parameters.md
      - usage/4-request-body.md
      - usage/5-responses.md
      - usage/6-dependency-injection.md
      - usage/7-middleware.md
      - usage/8-authentication.md
      - usage/9-guards.md
      - Plugins:
          - usage/10-plugins/0-plugins-intro.md
          - usage/10-plugins/1-sql-alchemy-plugin.md
          - usage/10-plugins/2-tortoise-orm-plugin.md
          - usage/10-plugins/3-piccolo-orm-plugin.md
      - usage/11-data-transfer-objects.md
      - usage/12-openapi.md
      - usage/13-lifecycle-hooks.md
      - usage/14-testing.md
      - usage/15-templating.md
      - usage/16-caching.md
      - usage/17-exceptions.md
  - migration.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/X3FJqy8d2j
    - icon: fontawesome/brands/github
      link: https://github.com/starlite-api/starlite
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
