[tool.poetry]
name = "starlite"
version = "1.41.0"
description = "Performant, light and flexible ASGI API Framework"
authors = ["Na'aman Hirschfeld <nhirschfeld@gmail.com>"]
maintainers = [
    "Na'aman Hirschfeld <nhirschfeld@gmail.com>",
    "Peter Schutt <peter.github@proton.me>",
    "Cody Fincher <cody.fincher@gmail.com>",
    "Janek Nouvertné <provinzkraut@posteo.de>",
    "Konstantin Mikhailov <konstantin.mikhailov@proton.me>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/starlite-api/starlite"
repository = "https://github.com/starlite-api/starlite"
documentation = "https://starlite-api.github.io/starlite"
keywords = ["api", "rest", "http", "asgi", "pydantic", "starlite", "framework", "websocket"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
]
include = ["CHANGELOG.md"]
packages = [
    { include = "starlite" },
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
aiomcache = { version = "*", optional = true }
anyio = ">=3"
brotli = { version = "*", optional = true }
cryptography = { version = "*", optional = true }
httpx = ">=0.22"
multidict = ">=6.0.2"
opentelemetry-instrumentation-asgi = { version = "*", optional = true }
orjson = "*"
picologging = { version = "*", optional = true }
pydantic = "*"
pydantic-factories = "*"
pydantic-openapi-schema = "*"
pyyaml = "*"
redis = { version = "*", optional = true, extras = ["hiredis"] }
starlite-multipart = ">=1.2.0"
structlog = { version = "*", optional = true }
typing-extensions = "*"

[tool.poetry.group.dev.dependencies]
aiomcache = "*"
aiosqlite = "*"
beanie = "*"
beautifulsoup4 = "*"
brotli = "*"
cryptography = "*"
fakeredis = "*"
freezegun = "*"
fsspec = "*"
greenlet = "*"
hypothesis = "*"
jinja2 = "*"
mako = "*"
mongomock-motor = "*"
opentelemetry-instrumentation-asgi = "*"
opentelemetry-sdk = "*"
piccolo = "*"
picologging = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
redis = "*"
sqlalchemy = "*"
starlette = "*"
structlog = "*"
tortoise-orm = "*"
tox = "*"
trio = "*"


[tool.poetry.extras]
brotli = ["brotli"]
cryptography = ["cryptography"]
full = ["brotli", "cryptography", "picologging", "structlog"]
memcached = ["aiomcache"]
opentelemetry = ["opentelemetry-instrumentation-asgi"]
picologging = ["picologging"]
redis = ["redis"]
structlog = ["structlog"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.MESSAGE_CONTROL]
disable = [
    "cyclic-import",
    "duplicate-code",
    "fixme",
    "import-outside-toplevel",
    "invalid-name",
    "line-too-long",
    "missing-class-docstring",
    "missing-module-docstring",
    "super-init-not-called",
    "too-few-public-methods",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-return-statements",
    "ungrouped-imports",
    "unnecessary-ellipsis",
    "unused-import",
    "protected-access",
]
enable = "useless-suppression"
extension-pkg-allow-list = ["pydantic", "orjson", "picologging"]

[tool.pylint.REPORTS]
reports = "no"

[tool.pylint.FORMAT]
max-line-length = "120"

[tool.pylint.VARIABLES]
ignored-argument-names = "args|kwargs|_|__"

[tool.pylint.BASIC]
no-docstring-rgx = "(__.*__|main|test.*|.*test|.*Test|^_.*)$"

[tool.pylint.LOGGING]
logging-modules = ["logging", "picologging", "structlog"]

[tool.coverage.run]
omit = ["*/tests/*"]

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'if TYPE_CHECKING:',
    'except ImportError as e:',
    'except ImportError:',
    '\.\.\.'
]

[tool.pytest.ini_options]
addopts = "--ignore=examples"
asyncio_mode = "auto"

[tool.pycln]
all = true

[tool.pyright]
include = ["starlite", "tests", "examples"]
exclude = [
    "starlite/plugins",
    "tests/plugins",
    "starlite/openapi",
    "tests/openapi",
    "examples/plugins/sqlalchemy_plugin"
]

[tool.slotscheck]
strict-imports = false

[tool.pydocstyle]
add-ignore = "D100,D104,D105,D106,D202,D205,D415"
add-select = "D401,D404,D417"
convention = "google"
match_dir = "starlite"

[tool.ruff]
exclude = [
  ".git",
  ".mypy_cache",
  ".nox",
  ".ruff_cache",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
  '__pycache__',
]
ignore = [
  'B008',
  'B009',
  'B010',
  'C408',
  'C417',
  'D100',
  'D104',
  'D105',
  'D106',
  'D202',
  "D203",
  "D204",
  "D205",
  "D213",
  "D215",
  "D400",
  "D404",
  "D406",
  "D407",
  "D408",
  "D409",
  "D413",
  "D415",
  'E501',
]
line-length = 120
select = [
  'B',
  'C',
  'D',
  'E',
  'F',
  'N',
  'W',
  'I',
  'U',
  'S',
  'FBT',
]
src = ["starlite", "tests/"]
target-version = "py38"
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fix = true

[tool.ruff.pep8-naming]
classmethod-decorators = [
  'classmethod',
  'validator',
  'root_validator',
  'declared_attr',
]

[tool.ruff.per-file-ignores]
"__init__.py" = ['F401']
"starlite/types/builtin_types.py" = ['F401']

[tool.ruff.isort]
known-first-party = ["starlite", 'tests']

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 12
