name: Documentation Building
on:
  push:
    branches: [starlite-theme]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: false
          installer-parallel: true
      - name: Install App Dependencies
        run: poetry install --no-interaction --with docs
      - name: Build docs
        run: poetry run python tools/build_docs.py docs-build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-build
