name: Documentation Building

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop
      - v3.0

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: refs/heads/main
            version: main
            condition: github.event_name == 'push'
          - branch: refs/heads/develop
            version: develop
            condition: github.event_name == 'push'
          - branch: refs/heads/v3.0
            version: 3-dev
            condition: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: pdm-project/setup-pdm@v4
        name: Set up PDM
        with:
          python-version: "3.12"
          allow-python-prereleases: false
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - name: Install dependencies
        run: pdm sync -G:all

      - name: Fetch gh pages
        run: git fetch origin gh-pages --depth=1

      - name: Build release docs
        run: pdm run python tools/build_docs.py docs-build
        if: github.event_name == 'release'

      - name: Build development docs
        if: ${{ matrix.condition && github.ref == matrix.branch }}
        run: pdm run python tools/build_docs.py docs-build --version ${{ matrix.version }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-build
