name: Latest Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify-issues:
    needs: publish-release
    name: Notify issues
    uses: ./.github/workflows/notify-released-issues.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}
